{
    'name' : 'XYZ University',
    'version' : '1.0',
    'summary': 'University Management',
    'sequence' : 5,
    'description' : 'XYZ University description.',
    'depends' : ['base','sale_management'],
    'data' : [
        'views/course_views.xml',
        'views/department_views.xml',
        'views/faculty_views.xml',
        'views/staff_views.xml',
        'views/student_views.xml',
        'views/university_views.xml',
        'views/staff_inherit_views.xml',
        'views/sale_inherit_views.xml',
        'views/sale_product_inherit_views.xml',
    ],
    'installable' : True,
    'application' : True,
    'auto_install' : False,
}