from . import course
from . import department
from . import faculty
from . import staff 
from . import student
from . import sale_inherit
from . import sale_product_inherit
from . import brand_dealer
from . import inherit_staff
from . import purchase_extend
from . import purchase_filter