from . import course
from . import department
from . import faculty
from . import staff 
from . import student
from . import staff_inherit
from . import sale_inherit
from . import sale_product_inherit
from . import brand_dealer